FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY Identity.Api/Identity.Api.csproj Identity.Api/
COPY Identity.Application/Identity.Application.csproj Identity.Application/
COPY Identity.Domain/Identity.Domain.csproj Identity.Domain/
COPY Identity.Infrastructure/Identity.Infrastructure.csproj Identity.Infrastructure/

RUN dotnet restore Identity.Api/Identity.Api.csproj

COPY . .
RUN dotnet publish Identity.Api/Identity.Api.csproj \
    --configuration Release \
    --no-restore \
    --output /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app
ENV ASPNETCORE_URLS=http://+:5001

COPY --from=build /app/publish .

EXPOSE 5001

ENTRYPOINT ["dotnet", "Identity.Api.dll"]
