using Catalog.Domain.Exceptions;
using Catalog.Domain.ValueObjects;

namespace Catalog.Domain.Aggregates;

/// <summary>
/// The <c>Title</c> aggregate root — the write-side model for a movie or show in
/// the catalog.
/// </summary>
/// <remarks>
/// This class enforces all invariants that the MongoDB schema cannot: required
/// fields, length caps, positive numeric ranges, and the rule that a title must
/// have at least one genre.  Infrastructure is responsible for mapping this class
/// to and from a MongoDB document via <c>BsonClassMap</c>; no driver types or
/// attributes appear here (ADR 0005, §2).
///
/// Read-side projections (TitleSummary, TitleDetail) are shaped in Application
/// and Infrastructure — they are never modelled here.  The CQRS query path
/// bypasses this aggregate entirely and projects straight from MongoDB (ADR 0005).
/// </remarks>
public sealed class Title
{
    // -------------------------------------------------------------------------
    // Invariant constants — named here rather than inlined as magic numbers (§16)
    // -------------------------------------------------------------------------

    /// <summary>Maximum character length for a title's display name.</summary>
    public const int MaxNameLength = 200;

    /// <summary>
    /// Minimum release year accepted; chosen to pre-date any plausible title
    /// in a real catalog while still catching obviously wrong values like 0 or
    /// negative years.
    /// </summary>
    public const int MinReleaseYear = 1888; // first known motion picture year

    /// <summary>Minimum valid duration, in minutes.  A title must have substance.</summary>
    public const int MinDurationMinutes = 1;

    // -------------------------------------------------------------------------
    // State — private setters so only aggregate methods can mutate
    // -------------------------------------------------------------------------

    /// <summary>Stable, externally-visible identifier for this title.</summary>
    public TitleId TitleId { get; private set; }

    /// <summary>Display name shown to subscribers.</summary>
    public string Name { get; private set; }

    /// <summary>Optional long-form description for the title's detail page.</summary>
    public string? Description { get; private set; }

    /// <summary>Genre labels this title belongs to.</summary>
    public IReadOnlyList<Genre> Genres { get; private set; }

    /// <summary>Year the title was originally released or first aired.</summary>
    public int ReleaseYear { get; private set; }

    /// <summary>Content rating governing who may view this title.</summary>
    public MaturityRating MaturityRating { get; private set; }

    /// <summary>
    /// Credited cast members, in presentation order.  May be empty for titles
    /// whose cast information is not yet available.
    /// </summary>
    public IReadOnlyList<string> Cast { get; private set; }

    /// <summary>
    /// Total runtime for a film, or average episode runtime for a series.
    /// </summary>
    public int DurationMinutes { get; private set; }

    /// <summary>
    /// Optional URL pointing to the title's poster artwork.  No URL format
    /// validation is performed here — format checking belongs at the API
    /// boundary (FluentValidation, §12).
    /// </summary>
    public string? PosterUrl { get; private set; }

    /// <summary>
    /// Loose cross-service reference to the Streaming service's manifest for
    /// this title.  Intentionally not validated here: if it is wrong, playback
    /// fails at the Streaming service, not in the Catalog domain (per openapi.yaml
    /// note on <c>streamingAssetId</c>).
    /// </summary>
    public string? StreamingAssetId { get; private set; }

    // -------------------------------------------------------------------------
    // Construction
    // -------------------------------------------------------------------------

    /// <summary>
    /// Creates a new <see cref="Title"/> with all required fields.
    /// </summary>
    /// <param name="titleId">Stable identifier, generated by the caller before persisting.</param>
    /// <param name="name">Display name; must be non-empty and at most <see cref="MaxNameLength"/> characters.</param>
    /// <param name="genres">At least one genre must be supplied.</param>
    /// <param name="releaseYear">Must be ≥ <see cref="MinReleaseYear"/> and ≤ the current calendar year.</param>
    /// <param name="maturityRating">Content rating label.</param>
    /// <param name="durationMinutes">Must be ≥ <see cref="MinDurationMinutes"/>.</param>
    /// <param name="description">Optional long-form description.</param>
    /// <param name="cast">Optional cast list; defaults to empty.</param>
    /// <param name="posterUrl">Optional poster URL.</param>
    /// <param name="streamingAssetId">Optional cross-service asset reference.</param>
    /// <exception cref="TitleValidationException">
    /// Thrown when any required-field invariant is violated.
    /// </exception>
    public Title(
        TitleId titleId,
        string name,
        IReadOnlyList<Genre> genres,
        int releaseYear,
        MaturityRating maturityRating,
        int durationMinutes,
        string? description = null,
        IReadOnlyList<string>? cast = null,
        string? posterUrl = null,
        string? streamingAssetId = null)
    {
        TitleId = titleId ?? throw new TitleValidationException(nameof(TitleId), "must not be null");

        ValidateName(name);
        ValidateGenres(genres);
        ValidateReleaseYear(releaseYear);
        ValidateDurationMinutes(durationMinutes);

        Name = name.Trim();
        Genres = genres;
        ReleaseYear = releaseYear;
        MaturityRating = maturityRating ?? throw new TitleValidationException(nameof(MaturityRating), "must not be null");
        DurationMinutes = durationMinutes;
        Description = description;
        Cast = cast ?? Array.Empty<string>();
        PosterUrl = posterUrl;
        StreamingAssetId = streamingAssetId;
    }

    // -------------------------------------------------------------------------
    // Behaviour
    // -------------------------------------------------------------------------

    /// <summary>
    /// Replaces all mutable metadata on this title with the supplied values.
    /// </summary>
    /// <remarks>
    /// The <see cref="TitleId"/> is intentionally excluded — identifiers are
    /// immutable once assigned.  This method re-runs the same invariant checks
    /// as the constructor so the aggregate cannot be put into an invalid state
    /// via an update path.
    /// </remarks>
    /// <param name="name">New display name.</param>
    /// <param name="genres">Replacement genre list; must contain at least one entry.</param>
    /// <param name="releaseYear">Replacement release year.</param>
    /// <param name="maturityRating">Replacement content rating.</param>
    /// <param name="durationMinutes">Replacement duration.</param>
    /// <param name="description">Optional replacement description.</param>
    /// <param name="cast">Optional replacement cast list.</param>
    /// <param name="posterUrl">Optional replacement poster URL.</param>
    /// <param name="streamingAssetId">Optional replacement streaming asset reference.</param>
    /// <exception cref="TitleValidationException">
    /// Thrown when any invariant is violated by the new values.
    /// </exception>
    public void UpdateMetadata(
        string name,
        IReadOnlyList<Genre> genres,
        int releaseYear,
        MaturityRating maturityRating,
        int durationMinutes,
        string? description = null,
        IReadOnlyList<string>? cast = null,
        string? posterUrl = null,
        string? streamingAssetId = null)
    {
        ValidateName(name);
        ValidateGenres(genres);
        ValidateReleaseYear(releaseYear);
        ValidateDurationMinutes(durationMinutes);

        Name = name.Trim();
        Genres = genres;
        ReleaseYear = releaseYear;
        MaturityRating = maturityRating ?? throw new TitleValidationException(nameof(MaturityRating), "must not be null");
        DurationMinutes = durationMinutes;
        Description = description;
        Cast = cast ?? Array.Empty<string>();
        PosterUrl = posterUrl;
        StreamingAssetId = streamingAssetId;
    }

    // -------------------------------------------------------------------------
    // Private invariant helpers — each checks exactly one rule (§5 SRP, §16)
    // -------------------------------------------------------------------------

    private static void ValidateName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new TitleValidationException(nameof(Name), "must not be empty");
        }

        if (name.Length > MaxNameLength)
        {
            throw new TitleValidationException(
                nameof(Name),
                $"must not exceed {MaxNameLength} characters");
        }
    }

    private static void ValidateGenres(IReadOnlyList<Genre> genres)
    {
        // A title with no genres cannot be meaningfully discovered by subscribers.
        if (genres is null || genres.Count == 0)
        {
            throw new TitleValidationException(nameof(Genres), "at least one genre is required");
        }
    }

    private static void ValidateReleaseYear(int releaseYear)
    {
        // Upper bound: a title cannot be released in a year that hasn't happened yet.
        var currentYear = DateTime.UtcNow.Year;

        if (releaseYear < MinReleaseYear || releaseYear > currentYear)
        {
            throw new TitleValidationException(
                nameof(ReleaseYear),
                $"must be between {MinReleaseYear} and {currentYear}");
        }
    }

    private static void ValidateDurationMinutes(int durationMinutes)
    {
        if (durationMinutes < MinDurationMinutes)
        {
            throw new TitleValidationException(
                nameof(DurationMinutes),
                $"must be at least {MinDurationMinutes} minute");
        }
    }
}
