FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY Subscription.Api/Subscription.Api.csproj Subscription.Api/
COPY Subscription.Application/Subscription.Application.csproj Subscription.Application/
COPY Subscription.Domain/Subscription.Domain.csproj Subscription.Domain/
COPY Subscription.Infrastructure/Subscription.Infrastructure.csproj Subscription.Infrastructure/

RUN dotnet restore Subscription.Api/Subscription.Api.csproj

COPY . .
RUN dotnet publish Subscription.Api/Subscription.Api.csproj \
    --configuration Release \
    --no-restore \
    --output /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app
ENV ASPNETCORE_URLS=http://+:5003

COPY --from=build /app/publish .

EXPOSE 5003

ENTRYPOINT ["dotnet", "Subscription.Api.dll"]
