using Profile.Domain.Exceptions;
using Profile.Domain.ValueObjects;

namespace Profile.Domain.Entities;

/// <summary>
/// Aggregate root for the Profile bounded context.
/// A profile belongs to exactly one account, identified by the accountId claim
/// in the caller's JWT (openapi.yaml lines 6-7).
/// Stored in ProfileDb (ADR 0001: one database per service, single SQL Server container).
/// </summary>
public sealed class UserProfile
{
    /// <summary>
    /// Opaque surrogate key generated by the domain on creation.
    /// A Guid avoids sequential leakage and requires no database round-trip at create time (ADR 0001).
    /// </summary>
    public ProfileId Id { get; }

    /// <summary>
    /// Foreign reference to the owning account in the Identity bounded context.
    /// Ownership checks use this value against the JWT claim.
    /// </summary>
    public AccountId AccountId { get; }

    /// <summary>
    /// User-visible label on the profile tile. Required, max 40 characters.
    /// </summary>
    public DisplayName DisplayName { get; private set; }

    /// <summary>
    /// Optional reference to an avatar image. Null when the user has not chosen one.
    /// </summary>
    public string? AvatarId { get; private set; }

    /// <summary>
    /// A kids profile restricts content to kid-safe maturity ratings.
    /// Defaults to false on creation (openapi.yaml CreateProfileRequest.isKidsProfile).
    /// </summary>
    public bool IsKidsProfile { get; }

    /// <summary>
    /// ISO 639-1 language code, e.g. "en". Null until explicitly set via update.
    /// </summary>
    public string? PreferredLanguage { get; private set; }

    /// <summary>
    /// Highest content rating this profile can browse, e.g. "PG-13". Null until explicitly set via update.
    /// </summary>
    public string? MaturityRating { get; private set; }

    public DateTime CreatedAtUtc { get; }

    private UserProfile(
        ProfileId id,
        AccountId accountId,
        DisplayName displayName,
        string? avatarId,
        bool isKidsProfile,
        string? preferredLanguage,
        string? maturityRating,
        DateTime createdAtUtc)
    {
        Id = id;
        AccountId = accountId;
        DisplayName = displayName;
        AvatarId = avatarId;
        IsKidsProfile = isKidsProfile;
        PreferredLanguage = preferredLanguage;
        MaturityRating = maturityRating;
        CreatedAtUtc = createdAtUtc;
    }

    /// <summary>
    /// The only legitimate way to create a new profile.
    /// The per-account limit (5) is an Application-layer concern (openapi.yaml lines 40-42)
    /// because it requires querying existing profile count — a repository concern.
    /// </summary>
    public static UserProfile Create(
        AccountId accountId,
        DisplayName displayName,
        string? avatarId,
        bool isKidsProfile = false)
    {
        return new UserProfile(
            ProfileId.New(),
            accountId,
            displayName,
            NormalizeOptionalString(avatarId),
            isKidsProfile,
            preferredLanguage: null,
            maturityRating: null,
            DateTime.UtcNow);
    }

    /// <summary>
    /// Reconstitutes a profile from persisted state (repository use only).
    /// Does not re-validate invariants that were enforced at creation time.
    /// </summary>
    public static UserProfile Reconstitute(
        ProfileId id,
        AccountId accountId,
        DisplayName displayName,
        string? avatarId,
        bool isKidsProfile,
        string? preferredLanguage,
        string? maturityRating,
        DateTime createdAtUtc)
    {
        return new UserProfile(
            id,
            accountId,
            displayName,
            avatarId,
            isKidsProfile,
            preferredLanguage,
            maturityRating,
            createdAtUtc);
    }

    /// <summary>
    /// Updates mutable profile fields. Validates that the caller owns this profile.
    /// </summary>
    /// <exception cref="ProfileNotOwnedException">
    /// Thrown when the caller's account does not match the profile's owner.
    /// </exception>
    public void Update(
        AccountId callerAccountId,
        DisplayName displayName,
        string? avatarId,
        string? preferredLanguage,
        string? maturityRating)
    {
        EnsureOwnership(callerAccountId);

        DisplayName = displayName;
        AvatarId = NormalizeOptionalString(avatarId);
        PreferredLanguage = NormalizeOptionalString(preferredLanguage);
        MaturityRating = NormalizeOptionalString(maturityRating);
    }

    /// <summary>
    /// Validates that the given account owns this profile.
    /// </summary>
    /// <exception cref="ProfileNotOwnedException">
    /// Thrown when the caller's account does not match the profile's owner.
    /// </exception>
    public void EnsureOwnership(AccountId callerAccountId)
    {
        if (AccountId != callerAccountId)
        {
            throw new ProfileNotOwnedException();
        }
    }

    /// <summary>
    /// Treats empty/whitespace-only strings as absent so the database column stays NULL
    /// rather than storing a meaningless blank value.
    /// </summary>
    private static string? NormalizeOptionalString(string? value)
    {
        return string.IsNullOrWhiteSpace(value) ? null : value.Trim();
    }
}
