using Identity.Domain.Exceptions;
using Identity.Domain.ValueObjects;

namespace Identity.Domain.Entities;

/// <summary>
/// Aggregate root for the Identity bounded context.
/// Owns the <see cref="RefreshToken"/> collection — no other aggregate touches it.
/// Stored in IdentityDb (ADR 0001: one database per service, single SQL Server container).
/// </summary>
public sealed class User
{
    private readonly List<RefreshToken> _refreshTokens = new();

    /// <summary>
    /// Opaque surrogate key generated by the domain on creation.
    /// A Guid avoids sequential leakage and requires no database round-trip at create time (ADR 0001).
    /// </summary>
    public UserId Id { get; }

    /// <summary>
    /// Validated, normalised email address.
    /// Uniqueness is enforced by the database; format validity is enforced here.
    /// </summary>
    public Email Email { get; private set; }

    /// <summary>Opaque hash produced by Infrastructure. The raw password never lives here.</summary>
    public PasswordHash PasswordHash { get; private set; }

    public DateTime CreatedAtUtc { get; }

    public IReadOnlyList<RefreshToken> RefreshTokens => _refreshTokens.AsReadOnly();

    private User(UserId id, Email email, PasswordHash passwordHash, DateTime createdAtUtc)
    {
        Id = id;
        Email = email;
        PasswordHash = passwordHash;
        CreatedAtUtc = createdAtUtc;
    }

    /// <summary>
    /// The only legitimate way to create a new user.
    /// Callers must supply an already-hashed password; hashing belongs in Infrastructure.
    /// </summary>
    public static User Create(Email email, PasswordHash passwordHash)
    {
        return new User(
            UserId.New(),
            email,
            passwordHash,
            DateTime.UtcNow);
    }

    /// <summary>
    /// Reconstitutes a user from persisted state (repository use only).
    /// Does not re-validate invariants that were enforced at creation time.
    /// </summary>
    public static User Reconstitute(
        UserId id,
        Email email,
        PasswordHash passwordHash,
        DateTime createdAtUtc,
        IEnumerable<RefreshToken> refreshTokens)
    {
        var user = new User(id, email, passwordHash, createdAtUtc);
        user._refreshTokens.AddRange(refreshTokens);
        return user;
    }

    /// <summary>
    /// Issues a new refresh token and attaches it to this user.
    /// The caller provides the token value; generation (cryptographic randomness) belongs in Application/Infrastructure.
    /// </summary>
    public RefreshToken IssueRefreshToken(string tokenValue, DateTime expiresAtUtc)
    {
        var token = RefreshToken.Create(tokenValue, expiresAtUtc, Id);
        _refreshTokens.Add(token);
        return token;
    }

    /// <summary>
    /// Implements the single-use rotation rule (openapi.yaml lines 91-93):
    /// the submitted token is revoked and a new one is issued atomically.
    /// </summary>
    /// <exception cref="InvalidRefreshTokenException">
    /// Thrown when the token is not found, already revoked, or expired.
    /// </exception>
    public RefreshToken RotateRefreshToken(string currentTokenValue, string newTokenValue, DateTime newExpiresAtUtc)
    {
        var existing = FindValidRefreshToken(currentTokenValue);
        existing.Revoke();
        return IssueRefreshToken(newTokenValue, newExpiresAtUtc);
    }

    /// <summary>
    /// Revokes a refresh token for logout (openapi.yaml lines 120-124).
    /// Deliberately does not require a live access token — the refresh token itself is the credential.
    /// An expired-but-not-revoked token is accepted here so logout works even after the session has ended.
    /// </summary>
    /// <exception cref="InvalidRefreshTokenException">
    /// Thrown only when the token is not found or is already revoked.
    /// Does NOT throw when the token has expired.
    /// </exception>
    public void RevokeRefreshToken(string tokenValue)
    {
        var token = _refreshTokens.FirstOrDefault(t => t.TokenValue == tokenValue)
            ?? throw new InvalidRefreshTokenException("Refresh token not found.");

        if (token.IsRevoked)
        {
            throw new InvalidRefreshTokenException("Refresh token has already been revoked.");
        }

        token.Revoke();
    }

    private RefreshToken FindValidRefreshToken(string tokenValue)
    {
        var token = _refreshTokens.FirstOrDefault(t => t.TokenValue == tokenValue)
            ?? throw new InvalidRefreshTokenException("Refresh token not found.");

        if (token.IsRevoked)
        {
            throw new InvalidRefreshTokenException("Refresh token has already been revoked.");
        }

        if (token.HasExpired)
        {
            throw new InvalidRefreshTokenException("Refresh token has expired.");
        }

        return token;
    }
}
